name: Build & Deploy Spring app
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    name: Build and Deploy Spring boot app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Unit Tests
        run: mvn -B test --file pom.xml
      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml